name: Run Packer Build on a Template File
on:
  pull_request:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest
    name: Build Custom Image with Packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
        
      - name: Check Packer Version
        run: packer -v
      
      - name: Add required plugins
        run: packer init .

      - name: Authenticate Google Cloud SDK
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SECRET_KEYS }}
      
      - name: zip the file
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'webapp.zip'
          exclusions: '*.git* /*node_modules/* '
        
      - name: Format Packer Template
        id: fmt
        run: packer fmt .
      
      - name: Decode Monitor auth JSON secret
        run: |
          echo "${{ secrets.MONITOR_AUTH }}" | base64 --decode > monitor_auth.json
          export MONITOR_AUTH=$(cat monitor_auth.json)
          echo "$MONITOR_AUTH"
      
        
      - name: Validate Packer Template
        id: validate
        run: |
          packer validate \
          -var 'PROJECT_ID=${{ secrets.PROJECT_ID }}' \
          -var 'SOURCE_IMAGE_FAMILY=${{ secrets.SOURCE_IMAGE_FAMILY }}' \
          -var 'SSH_USERNAME=${{ secrets.SSH_USERNAME }}' \
          -var 'IMAGE_NAME=${{ secrets.IMAGE_NAME }}' \
          -var 'IMAGE_FAMILY=${{ secrets.IMAGE_FAMILY }}' \
          -var 'ZONE=${{ secrets.ZONE }}' \
          -var "MONITOR_AUTH='$MONITOR_AUTH'" \
          packer_config.pkr.hcl
        
      - name: Run Packer Build
        run: |
          packer build \
          -var 'PROJECT_ID=${{ secrets.PROJECT_ID }}' \
          -var 'SOURCE_IMAGE_FAMILY=${{ secrets.SOURCE_IMAGE_FAMILY }}' \
          -var 'SSH_USERNAME=${{ secrets.SSH_USERNAME }}' \
          -var 'IMAGE_NAME=${{ secrets.IMAGE_NAME }}' \
          -var 'IMAGE_FAMILY=${{ secrets.IMAGE_FAMILY }}' \
          -var 'ZONE=${{ secrets.ZONE }}' \
          -var 'MONITOR_AUTH=${{secrets.MONITOR_AUTH}}' \
          -force \
          packer_config.pkr.hcl
  

