name: packer_validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer_validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
      
      - name: Format Packer Template
        id: fmt
        run: packer fmt .

      - name: Zip the Project
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'webapp.zip'
          exclusions: '*.git* /*node_modules/*'
      
      - name: Validate Packer Template
        id: validate
        run: packer validate .
    
