name: packer_validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer_validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Authenticate Google Cloud SDK
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SECRET_KEYS }}

      - name: Packer initialize
        run: packer init .
      
      - name: Format Packer Template
        id: fmt
        run: packer fmt .
      
      - name: Validate Packer Template
        id: validate
        run: packer validate .
    
